from typing import overload, List
from numpy.typing import NDArray
import numpy as np

@overload
def long_kaon_decay_spectrum(
    egam: float, ek: float, modes: List[str] = ...
) -> float: ...
@overload
def long_kaon_decay_spectrum(
    egam: NDArray[np.float64], ek: float, modes: List[str] = ...
) -> NDArray[np.float64]: ...
