from typing import overload, List
from numpy.typing import NDArray
import numpy as np

@overload
def short_kaon_decay_spectrum(
    egam: float, epi: float, modes: List[str] = ...
) -> float: ...
@overload
def short_kaon_decay_spectrum(
    egam: NDArray[np.float64], epi: float, modes: List[str] = ...
) -> NDArray[np.float64]: ...
